service: cerner-fhir-lambda

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    AUTH_URL: ${env:AUTH_URL}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}

functions:
  cernerFhirFunction:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /immunization
          method: get
          cors: true